# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.cache/wt [current_project]
set_property parent.project_path /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/sources_1/new/TX_control.sv
  /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/sources_1/new/TX_sequence.sv
  /home/nicolas/Escritorio/lab7_ME_reference/UART_RX_CTRL.sv
  /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/sources_1/new/UART_tx_control_wrapper.sv
  /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/sources_1/new/pb_debouncer.sv
  /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/sources_1/new/ME_top.sv
}
read_verilog -library xil_defaultlib {
  /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/sources_1/imports/new/bcd_to_ss.v
  /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/sources_1/imports/new/clk_divider.v
  /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/sources_1/imports/uart/data_sync.v
  /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/sources_1/imports/new/display_mux.v
  /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/sources_1/imports/uart/uart_basic.v
  /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/sources_1/imports/uart/uart_baud_tick_gen.v
  /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/sources_1/imports/uart/uart_rx.v
  /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/sources_1/imports/uart/uart_tx.v
  /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/sources_1/imports/new/unsigned_to_bcd.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/constrs_1/new/constraints_ME_lab7.xdc
set_property used_in_implementation false [get_files /home/nicolas/Escritorio/lab7_ME_reference/lab7_master_SV.srcs/constrs_1/new/constraints_ME_lab7.xdc]


synth_design -top ME_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ME_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ME_top_utilization_synth.rpt -pb ME_top_utilization_synth.pb"
